### ISSUE TITLE
unable to do npm install

### ISSUE THREAD

**Issue by syedirfan7** [SMARTRACTECHNOLOGY/lifecycles-utilize-app#13]
install was giving errors  for npm install ( "react-native-nfc-reader": "git+ssh://git@github.com/SMARTRACTECHNOLOGY/react-native-nfc-reader.git#fix-android",)

its breaking the installation at this instance and the above dependent git repo is not available ( "git+ssh://git@github.com/SMARTRACTECHNOLOGY/react-native-nfc-reader.git#fix-android",)

please enlighten this ...

**Comment by voor** [comment]
This should be resolved now, as that library is no longer used.
